### ISSUE TITLE
Update bundletool to 1.8.1 in gordon

### ISSUE THREAD

**Issue by SantiagoPerdomo0199** [Banno/Gordon#107]
**Before you open an issue**
- [X] Are you using [the latest Gordon version](https://github.com/Banno/Gordon/releases/latest)? If not, try updating.
- [X] Are you using [the latest Gradle version](https://gradle.org/releases)? If not, try updating. If you can't update your Gradle version, you may have to use an older Gordon version that supports the outdated Gradle version.
- [X] Are you using [the latest Android Gradle Plugin version](https://developer.android.com/studio/releases/gradle-plugin)? If not, try updating. If you can't update your AGP version, you may have to use an older Gordon version that supports the outdated AGP version.
- [X] Are you sure this is a bug? If it's a feature request or idea for improvement, or if you're just not sure that your problem is caused by a Gordon bug rather than something else, consider posting in the ["Ideas" or "Q&A" Discussion categories](https://github.com/Banno/Gordon/discussions) instead of opening an issue.

**Describe the bug**
There is an error with Android 12(Android12 emulator fails due to 'Error retrieving device density'), this error fixed at Bundletool 1.8.1, gordonMock task don't work because the version bundletool is 1.8.0 

**Expected behavior**
Update bundletool to 1.8.1 in gordon

**Additional context**

**Comment by joshschriever** [comment]
Fixed in [v1.8.3](https://github.com/Banno/Gordon/releases/tag/1.8.3)
