### ISSUE TITLE
Cannot  generate reports after run tests

### ISSUE THREAD

**Issue by gustavofc1997** [Banno/Gordon#11]
i'm gettings this error Caused by: org.xmlpull.v1.XmlPullParserException: No valid serializer classes found in resource /META-INF/services/org.xmlpull.v1.XmlPullParserFactory that contained 'org.xmlpull.mxp1.MXParser,org.xmlpull.mxp1_serializer.MXSerializer'

**Comment by joshschriever** [comment]
Fixed in [version 1.0.5](https://github.com/Banno/Gordon/releases/tag/1.0.5)
