### ISSUE TITLE
Support for Android Junit5

### ISSUE THREAD

**Issue by gopidholakia** [Banno/Gordon#124]
### Discussed in https://github.com/Banno/Gordon/discussions/123

<div type='discussions-op-text'>

<sup>Originally posted by **gopidholakia** August 28, 2023</sup>
Gordon can only support Junit4, it would be great if I get support for JUnit5 as well.

[android-junit5](https://github.com/mannodermaus/android-junit5)

what I have did to have the suppoert for JUnit5 is, edit TestSuiteLoader

**From**
`private val Annotatable.isTestMethod
    get() = annotationNames.any { it == "org.junit.Test" }`
    
**To**
`private val Annotatable.isTestMethod
    get() = annotationNames.any { it in setOf("org.junit.Test", "org.junit.jupiter.api.Test") }`
    
 This change is working for me, and It would be better if I get support by Gordon itself.
 
 </div>

**Comment by joshschriever** [comment]
See #125. Thanks @gopidholakia!

**Comment by joshschriever** [comment]
Released in [v1.10.0](https://github.com/Banno/Gordon/releases/tag/1.10.0)

**Comment by gopidholakia** [comment]
Thanks a lot! @joshschriever
