### ISSUE TITLE
Run annotated tests

### ISSUE THREAD

**Issue by PabloMGrela** [Banno/Gordon#15]
It would be nice if you can add the support to run test with specific annotations.

**Comment by joshschriever** [comment]
Done in [version 1.2.0](https://github.com/Banno/Gordon/releases/tag/1.2.0). See [README](https://github.com/Banno/Gordon/tree/483923de4f628ead592ce218b02a312003b588ae#compatibility-with-android-extension) for example of how to do it using testInstrumentationRunnerArguments.
