### ISSUE TITLE
adb host as parameter

### ISSUE THREAD

**Issue by QAutomatron** [Banno/Gordon#24]
`JadbConnection` supports using an external host for `adb` commands. It would be nice to have an option to set it from Gordon configuration. 

Use cases: access host machine from docker container. Or access devices from another host in network.

**Comment by joshschriever** [comment]
As of #39 we also use bundletool for installs, and I don't think that supports external adb host yet. There's [a PR for it](https://github.com/google/bundletool/pull/93), but that's stale. Hopefully eventually we can support this somehow.

**Comment by sleekweasel** [comment]
An alternative to telling bundletool how to talk to remote hosts that I didn't pursue because I got my patch working: run a proxy forwarding socket, something like 'socat', to give yourself a local port that connects to the remote machine.
