### ISSUE TITLE
Tests with @SdkSuppress annotation are displayed as failed

### ISSUE THREAD

**Issue by QAutomatron** [Banno/Gordon#25]
**Steps:**
Test method annotated with `@SdkSuppress(maxSdkVersion = 19)`.

**Actual result**
In reports (both HTML and JUnit) displayed as failed. 

**Expected result**
Maybe it should be marked as skipped.

```
DeprecatedScreenTest.testShouldRedirectToUpdateApplicationWhenDeprecated

Failure 1
Time: 0
OK (0 tests)

Failure 2
Time: 0.001
OK (0 tests)
```

**Comment by joshschriever** [comment]
Fixed in [version 1.2.0](https://github.com/Banno/Gordon/releases/tag/1.2.0)
