### ISSUE TITLE
Error with minSdkVersion 24

### ISSUE THREAD

**Issue by mreigosa** [Banno/Gordon#32]
After upgrading the app to use minSdkVersion 24 (Android 7.0 (API level 24)) the plugin is not working. Every time we try to run it I get the error:

`What went wrong:
Execution failed for task :app:gordonProd
bad magic value: 64 65 78 0a 30 33 37 00`

**Comment by joshschriever** [comment]
Fixed in [version 1.3.1](https://github.com/Banno/Gordon/releases/tag/1.3.1)
