### ISSUE TITLE
Support Annotation argument 

### ISSUE THREAD

**Issue by evaristokbza** [Banno/Gordon#34]
It would be nice if there was the option to run annotated tests filtered by an argument provided in command line. Something similar to what would be achieved by using: 
`./gradlew connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.annotation=com.example.CustomAnnotation`

`--test` only supports packages, clases or methods. 
Setting annotation in gradle is not flexible enough.

**Comment by joshschriever** [comment]
Released in [v1.4.1](https://github.com/Banno/Gordon/releases/tag/1.4.1)
