### ISSUE TITLE
Configuring with the old Gradle plugins syntax

### ISSUE THREAD

**Issue by cparracondor** [Banno/Gordon#4]
It would be great if you guys could show an example of how to set the configuration with the old Gradle plugins syntax. Is this possible? Thanks.

**Comment by joshschriever** [comment]
@cparracondor do you mean a groovy version of [this](https://github.com/Banno/Gordon#configuring)? If so, the only difference is you'd have to add `.INSTANCE` to the pooling strategy because `PoolingStrategy` is a Kotlin sealed class.
Example:
```
import com.banno.gordon.PoolingStrategy

gordon {
    poolingStrategy.set(PoolingStrategy.PhonesAndTablets.INSTANCE)
}
```

**Comment by cparracondor** [comment]
Thanks! This is what I needed.
