### ISSUE TITLE
Using AllDevices with a specific set of devices

### ISSUE THREAD

**Issue by langerhans** [Banno/Gordon#5]
Hi!
I haven't seen a way to specify a list of devices when using any of the pooling strategies besides SpecificDevices. Is there a way to do this for AllDevices too? 
My use case is that on my CI machine I run eight emulators and 4 Jenkins build processors. This means each build will be able to reserve two devices per run. If I am reading the source correct, AllDevices would just try to run my tests on all eight emulators. In Spoon I was able to just pass in a set of devices to use: `devices = [System.getenv("EMU_ONE"), System.getenv("EMU_TWO")]`.

**Comment by joshschriever** [comment]
That sounds like a use case we can add support for at some point! I'm thinking maybe deprecate `SpecificDevices` and add a `Manual` pooling strategy something like this:

`data class Manual(val poolNameToDeviceSerials: Map<String, Set<String>>) : PoolingStrategy()`

**Comment by dimkonomis** [comment]
Any update on this? Is it something we can expect soon?

**Comment by joshschriever** [comment]
@dimkonomis I'm hoping to get to this soon

**Comment by joshschriever** [comment]
Done in [version 1.2.0](https://github.com/Banno/Gordon/releases/tag/1.2.0)
