### ISSUE TITLE
Gordon is not running in multi module project

### ISSUE THREAD

**Issue by feguerrero** [Banno/Gordon#72]
Does Gordon support multi module projects? I'm getting this error:
```
<ij_msg_gr>Gradle import errors<ij_msg_gr><ij_nav>/Users/felipeerazo/AndroidStudioProjects/android-evercheck-2.0/app/build.gradle<ij_nav><i><b>project ':app': Unable to build Kotlin project configuration</b><eol>Details: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':app:gordonDevelopment'.<eol>Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'GordonTestTask'.<eol>Caused by: java.lang.NoSuchMethodError: org.gradle.api.provider.Property.zip(Lorg/gradle/api/provider/Provider;Ljava/util/function/BiFunction;)Lorg/gradle/api/provider/Provider;</i>
```

**Comment by joshschriever** [comment]
Yes, Gordon does support multi-module projects. That error looks like you're using an old Gradle version. Try updating to the latest Gradle version, or if you can't do that for some reason then you could try using an older version of Gordon.

**Comment by JoseJavierGuerrero** [comment]
Hey @feguerrero, try using Gradle wrapper version >= 6.6. Property::zip was introduced in this version.

**Comment by joshschriever** [comment]
@feguerrero I'm going to go ahead and close this. Feel free to reopen if using Gradle version >= 6.6 doesn't solve your problems!
