### ISSUE TITLE
"The APK Set archive does not contain the following modules" error message

### ISSUE THREAD

**Issue by grzechu92** [Banno/Gordon#73]
It looks like since Gordon is having dependency to bundletool newer than 0.15.0 using `--modules` parameter causes following error message:

```
The APK Set archive does not contain the following modules: [module_name]
```

It happens when dynamic feature module is configured with install-time delivery.

```
    <dist:module>
        <dist:delivery>
            <dist:install-time />
        </dist:delivery>
    </dist:module>
```

I'm not really sure if that's a thing on Gordon or bundletool side, but it seems like not calling `--modules` while executing `bundletool install-apks` is solving the issue, which makes sense, because maybe bundetool is not treating install-time modules as "modules" by definition.
Is that `--modules` verification necessary? Could it be omitted or optional by some configuration parameter?

**Comment by joshschriever** [comment]
Fixed in [v1.6.1](https://github.com/Banno/Gordon/releases/tag/1.6.1)
