### ISSUE TITLE
Fails to sync using Gradle 4.2.0

### ISSUE THREAD

**Issue by KevinButterfield** [Banno/Gordon#92]
After upgrading to gradle 4.2.0, Gordon prevents gradle sync with the following error message: 

```
java.lang.NoSuchMethodError: 'void com.android.build.api.dsl.CommonExtension.onVariants(kotlin.jvm.functions.Function1)'
	at com.banno.gordon.GordonPlugin.apply(GordonPlugin.kt:41)
	at com.banno.gordon.GordonPlugin.apply(GordonPlugin.kt:30) <162 internal calls>
```

This is reproducible from a freshly created android project.  Reverting to 4.1.3 or removing `'com.banno.gordon'` from applied plugins allows gradle to sync and Android Studio to build.

**Comment by joshschriever** [comment]
Fixes in [v1.6.5](https://github.com/Banno/Gordon/releases/tag/1.6.5)
